config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/calf_creek_horizon', to: 'home#show', as: :cch

  resources :info, only: [:index]
  get '/info/preforms', to: 'info#show', as: :preforms

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sites, only: [:index]
    end
  end

  get '/map', to: 'map#show', as: :map

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  namespace :admin do
    get '/dashboard', to: 'users#show', as: :dashboard
    resources :users, only: [:index]

    resources :artifacts, only: [:new, :create, :edit, :update, :destroy]
    resources :sites, only: [:new, :create, :edit, :update]
    resources :videos, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :artifacts, only: [:show]
  resources :sites, only: [:show, :index]
  resources :videos, only: [:index, :show]
  get '/:point_type', to: 'artifacts#index', as: :points

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, presence: true
  validates :link, presence: true

  def self.transform_link(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end
  end

  def self.youtube_embed(url)
    formatted_link = transform_link(url)
    %Q{<iframe title="YouTube video player" width="640" height="390" src="https://www.youtube.com/embed/#{ formatted_link }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:notice] = "#{@video.title} Saved!"
      redirect_to video_path(@video.id)
    else
      flash[:notice] = "Data is missing or invalid! Try again"
      redirect_to new_admin_video_path
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(video_params)
      flash[:alert] = "Video titled: '#{@video.title}' Updated!"
      redirect_to video_path(@video)
    else
      flash[:alert] = "Data is missing or invalid! Try again"
      redirect_to edit_admin_video_path(@video)
    end
  end

  def destroy
    video = Video.find(params[:id])
    video.destroy
    flash[:notice] = "Video titled: '#{video.title}' Deleted!"
    redirect_to videos_path
  end

  private

  def video_params
    params.require(:video).permit(:title, :description, :link)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @link = Video.youtube_embed(@video.link)
  end
end

app/views/videos/index.html.erb
<h2> Watch a Video</h2>

<div class="list-group">
  <% if admin_authenticated %>
    <p><%= link_to "Add a new Video", new_admin_video_path,
        class: "list-group-item active" %></p>
  <% end %>

  <% cache cache_key_for(Video, "list") do %>
    <% @videos.each do |video| %>
        <p><%= link_to video.title, video_path(video),
            class: "list-group-item" %></p>
    <% end %>
  <% end %>
</div>

app/views/videos/show.html.erb
<h2><%= @video.title %></h2>

<div class="row">
  <div class="col-md-7">
    <p><%= raw(@link) %></p>
  </div>
    <div class="col-md-4 content-box">
      <h3>Description</h3>
      <p><%= @video.description %></p>

      <% if admin_authenticated %>
      <div>
        <p><%= link_to "Edit Video", edit_admin_video_path(@video), class: "btn btn-primary" %></p>
        <p><%= link_to "Delete Video", admin_video_path(@video), method: :delete, data: { confirm: 'Are you sure you want to delete this video?' }, class: "btn btn-primary" %></p>
      </div>
      <% end %>
    </div>
</div>