config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/calf_creek_horizon', to: 'home#show', as: :cch

  resources :info, only: [:index]
  get '/info/preforms', to: 'info#show', as: :preforms

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sites, only: [:index]
    end
  end

  get '/map', to: 'map#show', as: :map

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  namespace :admin do
    get '/dashboard', to: 'users#show', as: :dashboard
    resources :users, only: [:index]

    resources :artifacts, only: [:new, :create, :edit, :update, :destroy]
    resources :sites, only: [:new, :create, :edit, :update]
    resources :videos, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :artifacts, only: [:show]
  resources :sites, only: [:show, :index]
  resources :videos, only: [:index, :show]
  get '/:point_type', to: 'artifacts#index', as: :points

end

app/views/shared/_calf_creek.html.erb
<h2>All Calf Creek Points</h2>
<div class="row">

  <div class="col-md-11">
    <% if admin_authenticated %>
        <%= link_to "Add a new Artifact", new_admin_artifact_path, class: "btn btn-primary" %>
    <% end %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Artifact UI</th>
          <th>Maximum Length</th>
          <th>Maximum Width</th>
          <th>Maximum Thickness</th>
          <th>Basal Edge Width</th>
          <th>Site</th>
        </tr>
      </thead>
      <tbody>
        <% @calf_creek.each do |calf_creek| %>
          <tr>
            <td> <%= calf_creek.ui %></td>
            <td> <%= calf_creek.max_length %> mm</td>
            <td> <%= calf_creek.max_width %> mm</td>
            <td> <%= calf_creek.max_thickness %> mm</td>
            <td> <%= calf_creek.basal_edge_width %> mm</td>
            <td> <%= calf_creek.site.name %></td>
          </tr>
          <% if admin_authenticated %>
          <tr>
            <td><%= link_to "Edit Artifact", edit_admin_artifact_path(calf_creek.id), class: "btn btn-primary" %></td>
            <td><%= link_to "Delete Artifact", admin_artifact_path(calf_creek.id), method: :delete, class: "btn btn-primary" %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%= react_component('Navbar', { user: current_user, admin: admin_authenticated }) %>

app/views/shared/_user_nav_buttons.html.erb
<div class="col-md-4">
  <%= link_to "Andice Points", points_path("Andice"), class: "btn btn-primary" %>
</div>
<div class="col-md-4">
  <%= link_to "Calf Creek Points", points_path("Calf Creek"), class: "btn btn-primary" %>
</div>
<div class="col-md-3">
  <%= link_to "Bell Points", points_path("Bell"), class: "btn btn-primary" %>
</div>