config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/calf_creek_horizon', to: 'home#show', as: :cch

  resources :info, only: [:index]
  get '/info/preforms', to: 'info#show', as: :preforms

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sites, only: [:index]
    end
  end

  get '/map', to: 'map#show', as: :map

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  namespace :admin do
    get '/dashboard', to: 'users#show', as: :dashboard
    resources :users, only: [:index]

    resources :artifacts, only: [:new, :create, :edit, :update, :destroy]
    resources :sites, only: [:new, :create, :edit, :update]
    resources :videos, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :artifacts, only: [:show]
  resources :sites, only: [:show, :index]
  resources :videos, only: [:index, :show]
  get '/:point_type', to: 'artifacts#index', as: :points

end

app/models/user.rb
class User < ActiveRecord::Base

  enum role: [:user, :admin]

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.first_name         = auth_info.info.first_name
      new_user.last_name          = auth_info.info.last_name
      new_user.email              = auth_info.info.email
    end
  end

  def first_visit
    self.created_at.strftime('%Y-%m-%d,%l:%M %p')
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def show
    @presenter = DashboardPresenter.new
  end

  def index
    @users = User.all
  end
end

app/views/admin/users/index.html.erb
<h2>All Users</h2>
<div class="row">

  <div class="col-md-11">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>First Visit</th>
        </tr>
      </thead>
      <tbody>
      <% cache cache_key_for(User, "list") do %>
        <% @users.each do |user| %>
          <tr>
            <td> <%= user.id %></td>
            <td> <%= user.first_name %></td>
            <td> <%= user.last_name %></td>
            <td> <%= user.email %></td>
            <td> <%= user.first_visit %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<h1> <%=current_user.first_name %>, welcome to your dashboard</h1>

<div class="list-group">
    <p class="list-group-item"><b>Total Number of Artifacts: <%= @presenter.artifact_count%></b></p>
    <p class="list-group-item"><b>Total Number of Sites: <%= @presenter.site_count %></b></p>

    <%= link_to "Add a new Artifact", new_admin_artifact_path,
        class: "list-group-item active" %>
    <%= link_to "Add a new Site", new_admin_site_path,
        class: "list-group-item active" %>
    <%= link_to "Add a new Video", new_admin_video_path,
        class: "list-group-item active" %>

    <%= link_to "#{@presenter.user_count} Current User(s)", admin_users_path,
        class: "list-group-item active" %>
</div>