config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/calf_creek_horizon', to: 'home#show', as: :cch

  resources :info, only: [:index]
  get '/info/preforms', to: 'info#show', as: :preforms

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sites, only: [:index]
    end
  end

  get '/map', to: 'map#show', as: :map

  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  namespace :admin do
    get '/dashboard', to: 'users#show', as: :dashboard
    resources :users, only: [:index]

    resources :artifacts, only: [:new, :create, :edit, :update, :destroy]
    resources :sites, only: [:new, :create, :edit, :update]
    resources :videos, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :artifacts, only: [:show]
  resources :sites, only: [:show, :index]
  resources :videos, only: [:index, :show]
  get '/:point_type', to: 'artifacts#index', as: :points

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

  def show
  end
end

app/views/info/index.html.erb
<main class="container">

  <%= link_to "Back", cch_path, class: "btn btn-primary" %>
  <%= link_to "CCH Preforms", preforms_path, class: "btn btn-primary"%>

  <h2>Calf Creek Horizon </h2>

  <div class="content-box center">
    <div class="welcome">
        <%= image_tag("Andice.jpg", class: "andice-image img-rounded shadow-element",
            id: "andice", alt: "Andice Point" ) %>
        <p>At the terminus of the Early Archaic there was a climatic deviation,
          a cooling episode. This appears to have stimulated bison populations
          <b>The Calf Creek Horizon (CCH)</b> is a cultural period that marks such a
          moment in time.</p>

        <p>The CCH (6,000 - 5,800 BP) is an Early-Middle Archaic
          to venture further afield than normal (Lohse et. al 2015)
          interval when foragers and bison hunters invested a great deal of time
          and skill in producing some of the more complex projectile points and
          notching technology in the archaeological record of North America.</p>

        <p><b>The Calf Creek, Andice, and Bell projectile</b> points are associated
          with the CCH and have been found in Arkansas, Kansas, Missouri,
          Oklahoma and Texas, and there is limited evidence in Colorado,
          New Mexico, northern Tamaulipas, and Utah.  Recently, rumors of Calf
          Creek points in the Dakotas have surfaced but scientific examination
          and confirmation by specialists has not occurred.</p>

        <p>The accumulated site
          data for the CCH peoples since the 1950's indicates that the extraordinary
          projectile point technologies they created may have been a technological
          response to changes in ecology, similar to a Revitalization Movement
          that has been discussed and proposed in connection with Clovis technology,
          13,500 - 13,000 BP (Bradley & Collins 2012).</p>

        <p>The regions associated with the Calf Creek points are north of the
          Red River up to central Missouri but more widely includes Colorado,
          Kansas, and more densely in Oklahoma, while the Andice and Bell
          points are related point technologies that dominate today's Texas and
          northern Mexico region.  Current research by the author is exploring
          the western fringes of the CCH and supportive technological research
          is providing better resolution of the manufacturing behaviors of the
          social groups north and south of the Red River.</p>

        <p>In this way it will
          be possible to shed light on a variety of questions such as where the
          technological ideas embedded in these point types began and which
          direction they spread, and what are the constellation of technological
          steps involved in these point types and how are they distinct or similar?
          Also, how much exchange and travel occurred across the geographic
          boundaries like the Rio Grande and Red River? Following the technological
          trail and the physical pathways that raw materials were transported,
          traded, and utilized throughout the southern Plains will help us
          understand the lifeways of the various social groups of this time and
          space within North America.</p>

        <p><b>Experimental replication work</b> is another component of this research
          and a section of this website will host information related to ongoing
          replication studies.  The author is an experimental flint knapper and
          will be posting up-to-date experimental work that sheds light the Calf
          Creek Horizon point types and other point types in the archaeological
          record.</p>
        <p><b>Stay tuned!</b></p>
    </div>
  </div>
</main>

app/views/info/show.html.erb
<%= link_to "Back", cch_path, class: "btn btn-primary" %>
<%= link_to "CCH Information", info_index_path, class: "btn btn-primary" %>

<h2>Calf Creek Horizon Preforms</h2>

<%= image_tag("cch_preforms.jpg", class: "welcome-image img-rounded", id: "preform", alt: "Preforms") %>